name: Firebase App Distribution

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFile: ${{ secrets.GOOGLE_SERVICES_JSON }}
          groups: alpha-testers
          file: app/build/outputs/apk/release/app-release.apk
          releaseNotes: |
            Where App - Alpha v1.0
            
            Changes in this build:
            - Initial testing release
            - Basic functionality implementation
            - Core features ready for testing 